import { attachDatabasePool } from "@vercel/functions";
import pg from "pg";

export type ServiceCentre = {
  id: number;
  name: string;
  email: string;
  phone: string | null;
  stripe_account_id: string | null;
  details_submitted: boolean;
  charges_enabled: boolean;
  payouts_enabled: boolean;
  becs_capability: string | null;
  // Set by a Halfshaft admin to block the workshop's logins. Debits on existing plans keep running.
  suspended_at: string | null;
  created_at: string;
  updated_at: string;
};

export type MembershipRole = "owner" | "staff";

export type Customer = {
  id: number;
  service_centre_id: number;
  full_name: string;
  email: string;
  phone: string | null;
  vehicle_rego: string | null;
  stripe_customer_id: string | null;
  created_at: string;
};

// "draft": waiting for the customer's bank details. "failed": debits are paused until
// the customer adds bank details that can be debited.
export type PlanStatus = "draft" | "active" | "completed" | "cancelled" | "failed";

export type PaymentPlan = {
  id: number;
  service_centre_id: number;
  customer_id: number;
  description: string;
  total_amount_cents: number;
  currency: string;
  instalment_count: number;
  frequency: "weekly" | "fortnightly" | "monthly";
  start_date: string;
  status: PlanStatus;
  stripe_payment_method_id: string | null;
  stripe_mandate_id: string | null;
  setup_token: string;
  checkout_session_id: string | null;
  activated_at: string | null;
  failure_reason: string | null;
  created_at: string;
};

export type InstalmentStatus = "scheduled" | "processing" | "paid" | "failed";

export type Instalment = {
  id: number;
  payment_plan_id: number;
  sequence: number;
  amount_cents: number;
  due_date: string;
  status: InstalmentStatus;
  stripe_payment_intent_id: string | null;
  paid_at: string | null;
  failure_reason: string | null;
  failure_code: string | null;
  attempt_count: number;
  last_attempt_at: string | null;
  // Set while an automatic retry is pending for a failed instalment.
  next_retry_on: string | null;
  created_at: string;
};

export type NotificationKind =
  | "plan_activated"
  | "debit_processing"
  | "debit_paid"
  | "debit_failed"
  | "debit_missed"
  | "bank_details_needed"
  | "bank_details_updated"
  | "plan_completed";

export type Notification = {
  id: number;
  service_centre_id: number;
  payment_plan_id: number | null;
  instalment_id: number | null;
  kind: NotificationKind;
  title: string;
  body: string;
  read_at: string | null;
  created_at: string;
};

// Timestamps are timestamptz and come back as ISO strings. Calendar dates (due dates,
// start dates, retry dates) are plain `date` columns and come back as YYYY-MM-DD.
const SCHEMA_V1 = `
CREATE TABLE service_centres (
  id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name               text NOT NULL,
  email              text NOT NULL UNIQUE,
  phone              text,
  stripe_account_id  text UNIQUE,
  details_submitted  boolean NOT NULL DEFAULT false,
  charges_enabled    boolean NOT NULL DEFAULT false,
  payouts_enabled    boolean NOT NULL DEFAULT false,
  becs_capability    text,
  suspended_at       timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE customers (
  id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_centre_id  integer NOT NULL REFERENCES service_centres(id) ON DELETE CASCADE,
  full_name          text NOT NULL,
  email              text NOT NULL,
  phone              text,
  vehicle_rego       text,
  stripe_customer_id text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  UNIQUE (service_centre_id, email)
);

CREATE TABLE payment_plans (
  id                       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_centre_id        integer NOT NULL REFERENCES service_centres(id) ON DELETE CASCADE,
  customer_id              integer NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  description              text NOT NULL,
  total_amount_cents       integer NOT NULL CHECK (total_amount_cents > 0),
  currency                 text NOT NULL DEFAULT 'aud',
  instalment_count         integer NOT NULL CHECK (instalment_count > 0),
  frequency                text NOT NULL CHECK (frequency IN ('weekly', 'fortnightly', 'monthly')),
  start_date               date NOT NULL,
  status                   text NOT NULL DEFAULT 'draft'
                             CHECK (status IN ('draft', 'active', 'completed', 'cancelled', 'failed')),
  stripe_payment_method_id text,
  stripe_mandate_id        text,
  -- The private token in the customer's plan link (/pay/<token>).
  setup_token              text NOT NULL UNIQUE,
  checkout_session_id      text,
  activated_at             timestamptz,
  -- Why debits are paused.
  failure_reason           text,
  created_at               timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE instalments (
  id                       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_plan_id          integer NOT NULL REFERENCES payment_plans(id) ON DELETE CASCADE,
  sequence                 integer NOT NULL,
  amount_cents             integer NOT NULL CHECK (amount_cents > 0),
  due_date                 date NOT NULL,
  status                   text NOT NULL DEFAULT 'scheduled'
                             CHECK (status IN ('scheduled', 'processing', 'paid', 'failed')),
  stripe_payment_intent_id text,
  paid_at                  timestamptz,
  failure_reason           text,
  failure_code             text,
  -- Part of the Stripe idempotency key for each debit.
  attempt_count            integer NOT NULL DEFAULT 0,
  last_attempt_at          timestamptz,
  next_retry_on            date,
  created_at               timestamptz NOT NULL DEFAULT now(),
  UNIQUE (payment_plan_id, sequence)
);

-- Workshop staff logins. Customers get their own, separate login tables later.
CREATE TABLE users (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL,
  email         text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE memberships (
  user_id           integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  service_centre_id integer NOT NULL REFERENCES service_centres(id) ON DELETE CASCADE,
  role              text NOT NULL CHECK (role IN ('owner', 'staff')),
  created_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, service_centre_id)
);

-- Only a SHA-256 hash of each session token is stored; the raw token lives in the cookie.
CREATE TABLE user_sessions (
  token_hash text PRIMARY KEY,
  user_id    integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Stripe webhook events already handled. Stripe can deliver an event more than once.
CREATE TABLE stripe_events (
  id          text PRIMARY KEY,
  type        text NOT NULL,
  account     text,
  received_at timestamptz NOT NULL DEFAULT now()
);

-- Payment updates shown in each workshop's Activity feed. The dedupe key stops the
-- webhook and the reconciliation pass from recording the same update twice.
CREATE TABLE notifications (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_centre_id integer NOT NULL REFERENCES service_centres(id) ON DELETE CASCADE,
  payment_plan_id   integer REFERENCES payment_plans(id) ON DELETE CASCADE,
  instalment_id     integer REFERENCES instalments(id) ON DELETE CASCADE,
  kind              text NOT NULL,
  title             text NOT NULL,
  body              text NOT NULL,
  dedupe_key        text NOT NULL UNIQUE,
  read_at           timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now()
);

-- Emails waiting to be sent to workshops and customers.
CREATE TABLE email_outbox (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_centre_id integer REFERENCES service_centres(id) ON DELETE CASCADE,
  notification_id   integer REFERENCES notifications(id) ON DELETE CASCADE,
  audience          text NOT NULL CHECK (audience IN ('workshop', 'customer')),
  recipient         text NOT NULL,
  subject           text NOT NULL,
  text_body         text NOT NULL,
  status            text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed', 'skipped')),
  attempts          integer NOT NULL DEFAULT 0,
  last_error        text,
  sent_at           timestamptz,
  dedupe_key        text NOT NULL UNIQUE,
  created_at        timestamptz NOT NULL DEFAULT now()
);

-- Halfshaft's own staff. Kept apart from workshop logins on purpose.
CREATE TABLE admins (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL,
  email         text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE admin_sessions (
  token_hash text PRIMARY KEY,
  admin_id   integer NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Every change an admin makes, and who made it.
CREATE TABLE admin_audit_log (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id          integer REFERENCES admins(id) ON DELETE SET NULL,
  action            text NOT NULL,
  service_centre_id integer REFERENCES service_centres(id) ON DELETE SET NULL,
  payment_plan_id   integer REFERENCES payment_plans(id) ON DELETE SET NULL,
  detail            text,
  created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_customers_centre           ON customers (service_centre_id);
CREATE INDEX idx_plans_centre               ON payment_plans (service_centre_id);
CREATE INDEX idx_plans_customer             ON payment_plans (customer_id);
CREATE INDEX idx_plans_mandate              ON payment_plans (stripe_mandate_id);
CREATE INDEX idx_instalments_due            ON instalments (payment_plan_id, due_date);
CREATE INDEX idx_instalments_status         ON instalments (status, due_date);
CREATE INDEX idx_instalments_payment_intent ON instalments (stripe_payment_intent_id);
CREATE INDEX idx_memberships_centre         ON memberships (service_centre_id);
CREATE INDEX idx_user_sessions_user         ON user_sessions (user_id);
CREATE INDEX idx_admin_sessions_admin       ON admin_sessions (admin_id);
CREATE INDEX idx_notifications_centre       ON notifications (service_centre_id, created_at);
CREATE INDEX idx_email_outbox_status        ON email_outbox (status);
CREATE INDEX idx_email_outbox_centre        ON email_outbox (service_centre_id, created_at);
CREATE INDEX idx_admin_audit_log_created    ON admin_audit_log (created_at);
`;

// Each run of the scheduled debit job, so a scheduler that has stopped calling it shows up.
const SCHEMA_V2 = `
CREATE TABLE job_runs (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job         text NOT NULL,
  trigger     text NOT NULL,
  as_of       date,
  started_at  timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  result      jsonb,
  error       text
);

CREATE INDEX idx_job_runs_started ON job_runs (job, started_at);
`;

// Text messages to customers (plan links, payment reminders, failed payments), and one-time
// links for workshop staff who forgot their password.
const SCHEMA_V3 = `
CREATE TABLE sms_outbox (
  id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_centre_id   integer REFERENCES service_centres(id) ON DELETE CASCADE,
  notification_id     integer REFERENCES notifications(id) ON DELETE CASCADE,
  -- Australian mobile in international format, e.g. +61412345678.
  recipient           text NOT NULL,
  body                text NOT NULL,
  status              text NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'sending', 'sent', 'failed', 'skipped')),
  attempts            integer NOT NULL DEFAULT 0,
  last_attempt_at     timestamptz,
  last_error          text,
  provider_message_id text,
  sent_at             timestamptz,
  dedupe_key          text NOT NULL UNIQUE,
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_sms_outbox_status ON sms_outbox (status);
CREATE INDEX idx_sms_outbox_centre ON sms_outbox (service_centre_id, created_at);

-- Only a SHA-256 hash of each reset token is stored; the raw token is in the emailed link.
CREATE TABLE password_resets (
  token_hash text PRIMARY KEY,
  user_id    integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at timestamptz NOT NULL,
  used_at    timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_password_resets_user ON password_resets (user_id, created_at);
`;

// Failed sign-in attempts, and the customer's own login: a code emailed or texted to them,
// so customers never need a password.
const SCHEMA_V4 = `
CREATE TABLE auth_attempts (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope      text NOT NULL,
  -- The email address being tried, or "ip:1.2.3.4".
  identifier text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_auth_attempts_lookup ON auth_attempts (scope, identifier, created_at);

-- Customers sign in with their email address; one session covers every workshop they owe.
CREATE TABLE customer_sessions (
  token_hash text PRIMARY KEY,
  email      text NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_customer_sessions_email ON customer_sessions (email);

-- Only a hash of each sign-in code is stored, like session and reset tokens.
CREATE TABLE customer_login_codes (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      text NOT NULL,
  code_hash  text NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at    timestamptz,
  attempts   integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_customer_login_codes_email ON customer_login_codes (email, created_at);
`;

// Invitations for more Halfshaft staff. The invited person sets their own password, so
// nobody has to send one around.
const SCHEMA_V5 = `
CREATE TABLE admin_invites (
  token_hash text PRIMARY KEY,
  email      text NOT NULL,
  name       text NOT NULL,
  invited_by integer REFERENCES admins(id) ON DELETE SET NULL,
  expires_at timestamptz NOT NULL,
  used_at    timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_admin_invites_email ON admin_invites (email, created_at);
`;

// Applied in order, once each. Never edit a migration that has shipped; add a new one.
const MIGRATIONS = [SCHEMA_V1, SCHEMA_V2, SCHEMA_V3, SCHEMA_V4, SCHEMA_V5];

// The start of the current month in Sydney, for "this month" totals.
export const SYDNEY_MONTH_START =
  "(date_trunc('month', now() AT TIME ZONE 'Australia/Sydney') AT TIME ZONE 'Australia/Sydney')";

// Return values the app can pass straight to React and JSON: counts and sums as numbers
// (not strings), dates as YYYY-MM-DD (not local-time Date objects), timestamps as ISO strings.
const OID = { INT8: 20, NUMERIC: 1700, DATE: 1082, TIMESTAMPTZ: 1184 };
const parseTimestamptz = pg.types.getTypeParser(OID.TIMESTAMPTZ);
const PARSERS: Record<number, (value: string) => unknown> = {
  [OID.INT8]: Number,
  [OID.NUMERIC]: Number,
  [OID.DATE]: (value) => value,
  [OID.TIMESTAMPTZ]: (value) => (parseTimestamptz(value) as Date).toISOString(),
};
const types = {
  getTypeParser: ((oid: number, format?: "text" | "binary") =>
    PARSERS[oid] ?? pg.types.getTypeParser(oid, format)) as typeof pg.types.getTypeParser,
};

export type Sql = {
  query<T>(text: string, params?: unknown[]): Promise<T[]>;
  one<T>(text: string, params?: unknown[]): Promise<T | undefined>;
  // Runs a statement and returns the number of rows it changed.
  run(text: string, params?: unknown[]): Promise<number>;
};

function sqlFor(execute: (text: string, params?: unknown[]) => Promise<pg.QueryResult>): Sql {
  return {
    async query<T>(text: string, params?: unknown[]) {
      return (await execute(text, params)).rows as T[];
    },
    async one<T>(text: string, params?: unknown[]) {
      return (await execute(text, params)).rows[0] as T | undefined;
    },
    async run(text: string, params?: unknown[]) {
      return (await execute(text, params)).rowCount ?? 0;
    },
  };
}

async function migrate(pool: pg.Pool) {
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    // Serverless instances can start at the same moment; only one applies migrations.
    await client.query("SELECT pg_advisory_xact_lock(4273001)");
    await client.query(
      "CREATE TABLE IF NOT EXISTS schema_migrations (version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now())",
    );
    const { rows } = await client.query<{ version: number }>(
      "SELECT COALESCE(MAX(version), 0) AS version FROM schema_migrations",
    );
    for (let version = rows[0].version + 1; version <= MIGRATIONS.length; version++) {
      await client.query(MIGRATIONS[version - 1]);
      await client.query("INSERT INTO schema_migrations (version) VALUES ($1)", [version]);
    }
    await client.query("COMMIT");
  } catch (err) {
    await client.query("ROLLBACK").catch(() => {});
    throw err;
  } finally {
    client.release();
  }
}

// Cached on globalThis so dev-server hot reloads reuse one pool.
const globalForDb = globalThis as unknown as { __halfshaftDb?: { pool: pg.Pool; ready: Promise<void> } };

async function getPool(): Promise<pg.Pool> {
  let state = globalForDb.__halfshaftDb;
  if (!state) {
    // Vercel's Neon integration writes the connection string under a prefixed name when a
    // prefix was set while connecting the database, e.g. DATABASE_URL_POSTGRES_URL. Both
    // of those are the pooled connection.
    // A variable that exists but is empty counts as unset: Vercel keeps a variable with a
    // blank value, which would otherwise win over Neon's.
    const connectionString = [
      process.env.DATABASE_URL,
      process.env.DATABASE_URL_POSTGRES_URL,
      process.env.POSTGRES_URL,
    ].find((value) => value && value.trim().length > 0);
    if (!connectionString) {
      // Names only, never values: this tells a deployment which database variables reached it.
      const visible =
        Object.keys(process.env)
          .filter((name) => /DATABASE|POSTGRES|^PG/.test(name))
          .sort()
          .join(", ") || "none";
      throw new Error(
        `DATABASE_URL isn't set. Database variables visible to this deployment: ${visible}. Locally, \`npm run dev\` starts a Postgres database for you.`,
      );
    }
    const pool = new pg.Pool({ connectionString, types, max: 5, idleTimeoutMillis: 10_000 });
    pool.on("error", (err) => console.error("Idle Postgres connection failed:", err));
    // On Vercel, closes idle connections before a function instance is suspended.
    attachDatabasePool(pool);

    const current = { pool, ready: migrate(pool) };
    current.ready.catch(() => {
      // Let the next request try again rather than caching the failure.
      if (globalForDb.__halfshaftDb === current) globalForDb.__halfshaftDb = undefined;
      pool.end().catch(() => {});
    });
    globalForDb.__halfshaftDb = state = current;
  }
  await state.ready;
  return state.pool;
}

export const db: Sql = sqlFor(async (text, params) => (await getPool()).query(text, params));

// Runs fn in one transaction. Everything inside must use `tx`, not `db`: a query on
// another connection can wait forever on a row this transaction has locked.
export async function transaction<T>(fn: (tx: Sql) => Promise<T>): Promise<T> {
  const client = await (await getPool()).connect();
  let broken = false;
  try {
    await client.query("BEGIN");
    const result = await fn(sqlFor((text, params) => client.query(text, params)));
    await client.query("COMMIT");
    return result;
  } catch (err) {
    await client.query("ROLLBACK").catch(() => {
      broken = true;
    });
    throw err;
  } finally {
    client.release(broken);
  }
}

export function isUniqueViolation(err: unknown): boolean {
  return err instanceof Error && "code" in err && err.code === "23505";
}

// For scripts: closes the pool so the process can exit.
export async function closeDb() {
  const state = globalForDb.__halfshaftDb;
  globalForDb.__halfshaftDb = undefined;
  if (state) await state.pool.end();
}
